server:
  port: 28080
  error:
    include-exception: true
    include-stacktrace: always

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  pattern:
    console: '%clr(${LOG_LEVEL_PATTERN:%-5p}) %clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${PID:%-5p}){magenta} %clr([%-25.25t]){faint} %clr(%logger::%method \(%file:%line\)){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
  level:
    org:
      netlykos: TRACE
